analogdevicesinc/Pixelpulse2

- qml/SignalRow.qml
This fixes the drag-to-pan functionality that is probably the most desirable click action.
It changes drag-to-compare to be middle-click drag. Alternatives include ctrl-drag, or finding a workaround to detect a double-click while passing other events through.
> Timeline drag/zoom fixes

- qml/DragDot.qml
- qml/OverlayPeriodic.qml
The main user-visible effect is that you can now click within a 4px radius of a dot to drag it, even if that is outside of the plot area. (Dots were previously very hard to grab at Y=0).
It also tweaks the positioning of the third (duty cycle) dot on square waves to be more obvious about what it does.
> Refactor DragDots

- Plot/FloatBuffer.h
- Plot/PhosphorRender.cpp
- SMU.cpp
Fixes:
- unused variables
- comparison between different data types
- the order of members initializers for a contructor
Signed-off-by: Dan Nechita <Dan.Nechita@analog.com>
> Fix C++ compile warnings

- qml/Controller.qml
- qml/Toolbar.qml
This is part of overhauling pixelpulse2 timing - ensuring that sample rates are determined via libsmu, removing options for adjusting sample rate, etc.
Begins to address #30.
> improve timing ux

- SMU.cpp
This is a fairly basic PR to be merged after testing on Windoze. It should groom m_available_devices on device detach, but with Windows.... who knows.
> Destroy available

- SMU.cpp
Deal with rounded-up sample counts from libsmu.
> Fix flicker on right-hand side of sample period.

- README.md
- main.cpp
On Linux, the file pixelpulse2.conf is written to directory "Unknown Organization" under ~/.config/ because the application doesn't set any organization name.  This 1-line addition to main.cpp sets QCore's organization to the name of the program, which is the standard convention for directories under ~/.config/ .
After the change, the config file will instead be written to ~/.config/pixelpulse2/pixelpulse2.conf
> Prevent config being written to ~/.config/Unknown Organization/pixelpulse2.conf

- .travis.yml
As per https://github.com/analogdevicesinc/Pixelpulse2/issues/142, need to use macdeployqtfix.py to fix the .app generated by qmake, prior to packing as a .dmg.
> fix OSX nightly builds via Travis-CI

- qml/dataexport.js
Empty `object`s are evaluated as `true` not `false` in JS.
The iteration loop 
` for (var i = 0; i < session.devices.length; i++) `
never breaks if `session.devices.length == 0`, resulting in an out of memory error.
This is addressed by explicitly checking session.devices.length before entering the loop.
> fix bug in dataexport.js

- appveyor.yml
SSL-related error messages were being printed to the console on Windows. As no executable code was being loaded over the network, SSL was merely "nice to have," not required, and these messages could be safely ignored.
As automatic firmware updating makes it into master, version numbers, checksums, and binary blobs should be loaded only over a secured connection. Given how broken the modern web of trust is, I'm considering certificate pinning via QSslSocket::addCaCertificate, but that might be overkill....
This pull request modifies the Appveyor build script to fetch Win32OpenSSL_Light and bundle the requisite DLLs into distrib.zip.
> Fix SSL on Windows

- pixelpulse2.pro
On systems with multiple versions of Qt installed, this generic
hardcoded path can be for a Qt version that doesn't correspond to the
qmake version being used. In this situation, the build often breaks due
to the incorrect QT_VERSION causing various conditional macros to error
out.
> pixelpulse2.pro: force qmake to determine the right header path

- appveyor.yml
This way, downloading the MinGW tools each time appveyor file changes
(since it was being cached) is no longer neccessary.
The downloaded version used to be 5.2.0 which didn't match the Qt
libraries that are built with MinGW 5.3.0.
> Appveyor: Use MinGW tools from Appveyor build environment

- Plot/FloatBuffer.h
- SMU.cpp
- SMU.h
- main.cpp
In the latest libsmu version we have changed the hotplug mechanism. This is because in the last versions of libusb, they have changed the way it works. On the latest versions, when a hotplug signal is emitted (and the callback is started), the device becomes busy, until the callback ends. This thing makes the hotplug mechanism from libsmu inoperative, because it is (almost) impossible to synchronize the callback end time and libsmu calls on the device. When this branch will be merged into master, we will not use the old version of libusb anymore and will use the latest available libusb version (link to the libusb github repository: https://github.com/libusb/libusb).
Therefore we have removed the hotplug_attach and hotplug_detach methods from libsmu and the "-p, --hotplug-devices" option …
> Removed libusb hotplug and solved the crash on close bug.

- SMU.cpp
Sometimes when unplugging a device from a multi-device session a deadlock occurred.
We have fixed this in libsmu and integrated the modifications in Pixelpulse.
Signed-off-by: Cristi Iacob <cristian.iacob@analog.com>
> Solved unplug deadlock bug.

- SMU.cpp
- SMU.h
- qml/Controller.qml
- qml/Toolbar.qml
Added data logging functionality.
One can now log the samples generated by Pixelpulse. 
How does it work? 
You can log the generated samples on a sample time of 1 or 10 seconds. The sample time is chosen from Pixelpulse's menu. If one of this sample times is checked, the data logging label becomes checkable. If you want to log the next session, you must check data logging from the menu. Every 1 or 10 seconds (depending on the sample time), the samples are logged.
How are the samples logged?
For each interval of time, the logger computes the minimum, maximum and average for the voltage and current from each device, on every channel. It also logs the device to which each data corresponds and the moment of time when the log was done (relative to the starting time). The file also includes on …
> Data logger

- SMU.cpp
Made a workaround for the libusb bug which appeared in libsmu on Windows.
This set is necessary in order to integrate this workaround.
Signed-off-by: Cristi Iacob <Cristian.Iacob@analog.com>
> Hotplug fix

- SMU.cpp
We now identify devices using a combination of
USB bus_id and USB address. This way we can detect if a running device
was disconnected (without interfering with the signal) or a new one was
connected.
After detecting that the device is already connected, we don't need to
delete the object, because it's the same one that's running a capture.
Signed-off-by: Alexandra Trifan <Alexandra.Trifan@analog.com>
> SMU.cpp: Modify the scanning process to align with changes in libsmu.

- SMU.cpp
- SMU.h
Improved the data logging mechanism. Before this update, the data logger was creating a new thread for each logging procedure, making it to run slower. I have implemented a thread pool in order to avoid this situation. 
This branch is rebased with the [release-build branch](https://github.com/analogdevicesinc/Pixelpulse2/tree/build-fixes) (in order to use the CMake build) so that #242 should be merged into master first.
> Data logging fix

- SMU.cpp
- main.cpp
The logged data was stored in the logging folder from Pixelpulse's default installation folder.
On most Windows machines, the installation folder was in C:/Program Files/Analog Devices, requiring admin privileges to write files here.
To avoid the admin permission issue, we have changed the logging folder to the AppData folder (C:\Users\<User>\AppData\Roaming\Pixelpulse2 and their equivalents for Linux and MacOS; more details about Qt's QStandardPaths::AppDataLocation [here](https://doc.qt.io/qt-5/qstandardpaths.html)).
Signed-off-by: Cristi Iacob <cristian.iacob@analog.com>
> SMU.cpp: change data logger write path.

- SMU.cpp
- SMU.h
- qml/DeviceRow.qml
You can now spot each device from the GUI by clicking each of the ADALM1000 labels from the left of the screen.
The corresponding device's leds will blink.
Signed-off-by: Cristi Iacob <cristian.iacob@analog.com>
> Added find device by led functionality.

- appveyor.yml
- pixelpulse2.iss.cmakein
Download the dpinst executable from swdownloads, to ensure the driver installation will always work properly (even if dpinst is missing from the target machine)
> Installer updates
